apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-credential
data:
  credentials: |
    [default]
    aws_access_key_id = AKIAWSKMPOVS5UGPOH22
    aws_secret_access_key = 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