apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: paulelie007/udagram-api-user:1.0
          resources:
            requests:
              cpu: 500m
              memory: 3012Mi
            limits:
              cpu: 500m
              memory: 3012Mi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-pg-secrets
          volumeMounts:
            - mountPath: "/root/.aws/"
              name: aws-credential
      volumes:
        - name: aws-credential
          configMap: 
            name: aws-credential
