# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and push images CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker-compose -f docker-compose-build.yaml build --parallel
      - run: docker tag reverseproxy paulelie007/reverseproxy:1.0
      - run: docker tag udagram-api-user paulelie007/udagram-api-user:1.0
      - run: docker tag udagram-api-feed paulelie007/udagram-api-feed:1.0
      - run: docker tag udagram-frontend:local paulelie007/udagram-frontend:1.0
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker push paulelie007/reverseproxy:1.0
      - run: docker push paulelie007/udagram-api-user:1.0
      - run: docker push paulelie007/udagram-api-feed:1.0
      - run: docker push paulelie007/udagram-frontend:1.0

